apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: roam-public
spec:
  parentRefs:
    - name: default-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "roam.austinbayley.co.uk"
  rules:
    - matches:
        - path:
            type: Exact
            value: /health
        - path:
            type: PathPrefix
            value: /api/challenges
          method: GET
      backendRefs:
        - name: api
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: roam-protected
spec:
  parentRefs:
    - name: default-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "roam.austinbayley.co.uk"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: api
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: roam-admin
spec:
  parentRefs:
    - name: default-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "roam.austinbayley.co.uk"
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/users
          method: GET
        - path:
            type: PathPrefix
            value: /api/admin
      backendRefs:
        - name: api
          port: 80
