apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prod-activity-public
spec:
  parentRefs:
    - name: default-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "activity.austinbayley.co.uk"
  rules:
    - matches:
        - path:
            type: Exact
            value: /health
        - path:
            type: PathPrefix
            value: /challenges
          method: GET
      backendRefs:
        - name: api
          port: 80
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Access-Control-Allow-Origin
                value: "https://roam.austinbayley.co.uk"
              - name: Access-Control-Allow-Credentials
                value: "true"
              - name: Access-Control-Allow-Headers
                value: "Authorization, Content-Type, X-Requested-With"
              - name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prod-activity-protected
spec:
  parentRefs:
    - name: default-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "activity.austinbayley.co.uk"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: api
          port: 80
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Access-Control-Allow-Origin
                value: "https://roam.austinbayley.co.uk"
              - name: Access-Control-Allow-Credentials
                value: "true"
              - name: Access-Control-Allow-Headers
                value: "Authorization, Content-Type, X-Requested-With"
              - name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prod-activity-oauth
spec:
  parentRefs:
    - name: default-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "activity.austinbayley.co.uk"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /oauth2
      backendRefs:
        - name: oauth2-proxy
          namespace: prod-auth
          port: 4180
