apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: roam-backend
  namespace: roam
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: kube-system
  hostnames:
    - "roam.austinbayley.co.uk"
  rules:
    - matches:
        - path:
            value: "/api"
      backendRefs:
        - name: api
          port: 80
