# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "CGO_ENABLED=1 go build -o main ./cmd/server/main.go"
# Binary file yields from `cmd`.
bin = "main"
# Watch these filename extensions.
include_ext = ["go"]
# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]
# Exclude unchanged files.
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# This log file places in your tmp_dir.
log = "air.log"

[log]
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true