version: "3"
services:
  api:
    container_name: activity_api
    build: 
      context: ./
      dockerfile: ./docker-local.dockerfile
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./:/app
      - $HOME/.config/gcloud/:/config:ro
  mongo:
    container_name: activity_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
