version: "1"
services:
  api:
    build: ./Dockerfile-local
    env_file:
      - .env
    ports:
      - "8000:5000"
    volumes:
      - ./:/app
      - $HOME/.config/gcloud/:/config:ro
  mongo:
    image: mongo
    ports:
      - "27017:27017"
