version: "3"
services:
  api:
    container_name: activity_api
    build: 
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
  mongo:
    container_name: activity_db
    image: mongo:8.0.11
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
